[env:stable]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = ttgo-t1
framework = arduino
lib_deps = 
	tttapa/Control Surface@^2.1.0
	bodmer/TFT_eSPI@^2.5.43
monitor_speed = 115200

build_flags =
  -D USER_SETUP_LOADED=1      ; Tell TFT_eSPI to use these flags instead of User_Setup.h
  -D ST7789_DRIVER=1          ; Standard driver for TTGO built-in screens
  -D TFT_WIDTH=135            ; Screen width
  -D TFT_HEIGHT=240           ; Screen height
  -D CGRAM_OFFSET=1           ; Offset required for this specific screen
  -D TFT_MOSI=19              ; Data pin
  -D TFT_SCLK=18              ; Clock pin
  -D TFT_CS=5                 ; Chip Select pin
  -D TFT_DC=16                ; Data/Command pin
  -D TFT_RST=23               ; Reset pin
  -D TFT_BL=4                 ; Backlight pin
  -D LOAD_GLCD=1              ; Load default fonts
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1